# Generated by Django 3.1.5 on 2021-04-06 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weeklydessert', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question',
            new_name='week',
        ),
    ]
